services:
  app:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on: [mssql]
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Workshop!Pass123"
    ports: ["1433:1433"]
    volumes:
      - mssql-data:/var/opt/mssql
      - ../db:/docker-entrypoint-initdb.d
volumes:
  mssql-data:
